name: Premium Ad Clicker Runner

on:
  workflow_dispatch: # Taaki aap jab chahen Button daba kar start karein
  schedule:
    - cron: '0 */3 * * *' # Har 3 ghante baad ye khud chalega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

       - name: Set up Python
        uses: actions/setup-python@v4  # <--- "os-" hata dein
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-utils google-chrome-stable

      - name: Install Python Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Bot with Virtual Display
        env:
          GITHUB_ACTIONS: "true"
        run: |
          # xvfb-run aik fake screen banata hai taaki PyAutoGUI crash na ho
          xvfb-run --server-args="-screen 0 1920x1080x24" python ad_clicker.py --query "https://abr.ge/zz4y46"
